name: Create GitHub release with changelog and wheel

on:
  push:
    tags:
    - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@master
      with:
        python-version: '3.9'
    - uses: actions/setup-node@master
    - name: Run conventional-github-releaser
      run: npx conventional-github-releaser -p angular
      env:
        CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.CONVENTIONAL_GITHUB_RELEASER_TOKEN }}
    - name: Install poetry
      run: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - name: Install poetry-dynamic-versioning
      run: python -m pip install poetry-dynamic-versioning
    - name: Build dist
      run: $HOME/.poetry/bin/poetry build
    - name: Add wheel to release
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.whl
        tag: ${{ github.ref }}
        file_glob: true
