name: Publish package to pypi

on:
  push:
    tags:
    - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Install poetry
      run: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - name: Install dependencies
      run: |
        $HOME/.poetry/bin/poetry install --no-dev
    - name: Build dist
      run: $HOME/.poetry/bin/poetry build
    - name: Publish to pypi
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: jayanth_koushik
        password: ${{ secrets.PYPI_PASSWORD }}
    - name: Add wheel to release
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.whl
        tag: ${{ github.ref }}
        file_glob: true
