name: Publish package to pypi and add wheel to GitHub release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Install poetry
      run: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - name: Build dist
      run: $HOME/.poetry/bin/poetry build
  pypi-upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Publish to pypi
      run: $HOME/.poetry/bin/poetry publish -u jayanth_koushik -p $PYPI_PASSWORD
      env:
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  gh-release-upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Add wheel to release
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.whl
        tag: ${{ github.ref }}
        file_glob: true
