name: Publish package to pypi

on:
  push:
    tags:
    - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: '3.9'
    - name: Install poetry
      run: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - name: Install poetry-dynamic-versioning
      run: python -m pip install poetry-dynamic-versioning
    - name: Build dist
      run: $HOME/.poetry/bin/poetry build
    - name: Publish to pypi
      run: $HOME/.poetry/bin/poetry publish -u __token__ -p $PYPI_TOKEN
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
